server:
  port: 8081
  #192.168.28.239:81
wxserviceurl: "http://210.14.129.41:81/xbapi/weixin/"
msserviceurl: "http://210.14.129.41:8080/msxfInterface2/"
msshopcode: 20152389
ybshopcode: 10016083399
spring:
   datasource:
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@//192.168.28.239:1521/JH
     username: XBPOS
     password: XBPOSXBPOS
   redis:
     host: 127.0.0.1
     port: 6379
   application:
       name: service-wx
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/


